name: .NET

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'e-donate' }}
      run: |
        winpty docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        winpty heroku container:push web -a $APP_NAME
        winptyheroku container:release web -a $APP_NAME
