name: .NET

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'e-donate' }}
      working-directory: ../Dockerfile
      run: docker build -t aspnetapp .
